version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-postcomment
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL__ROOT_PASSWORD}
      MYSQL_DATABASE: social
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-postcomment
    # restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: minio-postcomment
    # restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO__ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO__ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: postcomment-api
    # restart: always
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"

    depends_on:
      - mysql
      - redis

  wrk:
    image: williamyeh/wrk
    container_name: wrk-benchmark
    depends_on:
      - api
    entrypoint: ["tail", "-f", "/dev/null"] # chạy nền để bạn exec vào

volumes:
  mysql_data:
  minio_data:
